name: npm test
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Installs Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Run install
        run: npm install
      - name: Run test
        run: npm test
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps: 
  #     - name: Checkout repo
  #       uses: actions/checkout@v4
  #     - name: Installs Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 'lts/*'
  #     - name: Run test
  #       run: npm test