name: interact with Github API
on: 
  pull_request:
jobs:
  create-issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: SHA reducing
        id: sha_reducing
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Create issue
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/issues \
          -d '{"title":"${{steps.sha_reducing.outputs.sha}}","body":"I'\''m having a problem with this.","labels":["bug"]}'
